const questions=[
{q:"Which of the following features of the Indian Constitution is borrowed from the Government of India Act, 1935?",o:["Directive Principles of State Policy","Federal scheme and office of Governor","Fundamental Duties","Procedure for amendment"],a:1,e:"The federal scheme, office of Governor, public service commissions and several administrative provisions draw from the Government of India Act, 1935."},
{q:"With reference to the Indian monsoon, which factor most directly contributes to the seasonal reversal of winds?",o:["Earth's rotation alone","Differential heating of land and sea","Ocean salinity","Mountain erosion"],a:1,e:"Seasonal differential heating creates pressure differences between the Asian landmass and surrounding oceans, helping drive monsoon circulation."},
{q:"The term 'stagflation' refers to a situation combining:",o:["High growth and low inflation","High inflation and stagnant growth","Deflation and high employment","Low inflation and high exports"],a:1,e:"Stagflation is characterized by persistent inflation occurring alongside weak or stagnant economic growth and often elevated unemployment."},
{q:"Who among the following is associated with the Permanent Settlement introduced in Bengal in 1793?",o:["Lord Cornwallis","Lord Dalhousie","Lord Wellesley","Warren Hastings"],a:0,e:"Lord Cornwallis introduced the Permanent Settlement in Bengal in 1793."},
{q:"Which constitutional body recommends the distribution of certain tax revenues between the Union and the States?",o:["Election Commission","Finance Commission","UPSC","NITI Aayog"],a:1,e:"Article 280 provides for the Finance Commission, including recommendations on tax distribution between the Union and States."},
{q:"The Western Ghats are significant for India's climate primarily because they:",o:["Create the Thar Desert","Cause orographic rainfall on their windward side","Block all winter winds","Generate cyclones in the Bay of Bengal"],a:1,e:"Moisture-laden southwest monsoon winds rise along the Western Ghats, producing substantial orographic rainfall on the western slopes."},
{q:"Which one is a Fundamental Duty under Article 51A of the Constitution?",o:["Right to equality","To develop scientific temper","Right to constitutional remedies","Right to property"],a:1,e:"Developing scientific temper, humanism and the spirit of inquiry and reform is a Fundamental Duty."},
{q:"In ecology, a 'keystone species' is best understood as a species that:",o:["Always has the largest population","Has a disproportionately large effect on its ecosystem","Lives only in deserts","Cannot be affected by habitat change"],a:1,e:"A keystone species can have an ecological effect far greater than its abundance alone would suggest."},
{q:"The Indus Valley Civilisation site of Dholavira is located in present-day:",o:["Rajasthan","Gujarat","Punjab","Haryana"],a:1,e:"Dholavira is located on Khadir island in the Rann of Kutch, Gujarat."},
{q:"If the Reserve Bank of India raises the repo rate, the immediate policy objective is generally to:",o:["Make borrowing cheaper","Tighten monetary conditions and help control inflation","Increase money supply rapidly","Reduce bank lending rates"],a:1,e:"A higher repo rate raises the cost of short-term funds for banks and is generally used to tighten monetary conditions and curb inflationary pressure."}
];
let current=0,answers=Array(questions.length).fill(null),seconds=1200,timerId;
const box=document.getElementById("quizBox"),bar=document.getElementById("progressBar");
function render(){const x=questions[current];box.innerHTML='<div class="question-number">QUESTION '+(current+1)+' OF '+questions.length+'</div><div class="question">'+x.q+'</div>'+x.o.map((v,i)=>'<button class="option '+(answers[current]===i?'selected':'')+'" onclick="choose('+i+')">'+String.fromCharCode(65+i)+'. '+v+'</button>').join('');bar.style.width=((current+1)/questions.length*100)+'%';document.getElementById("prev").style.visibility=current?'visible':'hidden';document.getElementById("next").textContent=current===questions.length-1?'Submit Quiz':'Next →'}
function choose(i){answers[current]=i;render()}
document.getElementById("prev").onclick=()=>{if(current>0){current--;render()}}
document.getElementById("next").onclick=()=>{if(current<questions.length-1){current++;render()}else finish()}
function finish(){clearInterval(timerId);let score=answers.reduce((n,a,i)=>n+(a===questions[i].a?1:0),0);document.getElementById("quiz").classList.add("hidden");document.getElementById("result").classList.remove("hidden");document.getElementById("scoreText").textContent='You scored '+score+' / '+questions.length;document.getElementById("resultMessage").textContent=score>=8?'Excellent analytical preparation. Keep revising concepts and current affairs.':score>=5?'Good foundation. Review the explanations and strengthen weak areas.':'Keep practising. Focus on core concepts before attempting advanced MCQs.';document.getElementById("result").scrollIntoView({behavior:"smooth"})}
function tick(){seconds--;if(seconds<0){finish();return}let m=String(Math.floor(seconds/60)).padStart(2,'0'),s=String(seconds%60).padStart(2,'0');document.getElementById("timer").textContent=m+':'+s}
function restartQuiz(){current=0;answers=Array(questions.length).fill(null);seconds=1200;document.getElementById("result").classList.add("hidden");document.getElementById("quiz").classList.remove("hidden");render();timerId=setInterval(tick,1000);document.getElementById("quiz").scrollIntoView({behavior:"smooth"})}
render();timerId=setInterval(tick,1000);